### ISSUE TITLE
Mention what the internal parameters are for higher io bandwidth

### ISSUE THREAD

**Issue by ianhi** [martinRenou/ipycanvas#102]
In https://ipycanvas.readthedocs.io/en/latest/basic_usage.html#optimizing-drawings you mention "internal jupyter parameters". It might be nice to be more specific about what these settings are. To get the error you mention I used
```python
for i in range(6000):
    canvas.fill_rect(25, 25, 100, 100)
```
to get:
```
IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)
```
### Proposed text:

This communication is limited to 1000 commands/s in any 3 second window if you did not change internal Jupyter parameters, and it can be extremely slow to send commands one after the other. To modify these start Jupyter with:
```
--NotebookApp.iopub_msg_rate_limt=<number of messages per second>
```
and/or
```
--NotebookApp.rate_limit_window=<window measure messaging rate (seconds)>
```
Do this at your own risk as these limits are in place to avoid crashing the notebook server.

**Comment by martinRenou** [comment]
Thanks for opening an issue. Although I agree it's better to give more information, the purpose of this paragraph was to say "You should prevent reaching this limit by using `hold_canvas` as much as possible".

I guess my point is that I don't want to encourage people to increase this limit.

Is this documented somewhere else? Maybe we could provide a link to it if people really want to increase the limit.

**Comment by ianhi** [comment]
> I guess my point is that I don't want to encourage people to increase this limit.

That seems extremely reasonable. I think I was being pathological when my first reaction to reading that was wondering how I can change it. 

> Is this documented somewhere else? Maybe we could provide a link to it if people really want to increase the limit.

I don't think so? Closest is probably https://stackoverflow.com/questions/43490495/how-to-set-notebookapp-iopub-data-rate-limit-and-others-notebookapp-settings-in I've also started an own unofficial widgets documentation for my own benefit and I wrote about it there (https://github.com/ianhi/custom-ipywidget-howto/blob/master/messaging-callbacks.md#message-rate-limits) but idk if either of those are appropriate places to link out to.

I think its fine as is but if you were to change I would suggest something like:

"This communication is limited to 1000 commands/s and it can be extremely slow to send commands one after the other. You can increase this limit via internal Jupyter parameters, however this is not recommended as it can lead to instability. Instead we provide `hold_canvas`....."

**Comment by ianhi** [comment]
Also: What does 
> `hold_canvas` must be used without moderation.

mean?

**Comment by martinRenou** [comment]
> I think its fine as is but if you were to change I would suggest something like:
"This communication is limited to 1000 commands/s and it can be extremely slow to send commands one after the other. You can increase this limit via internal Jupyter parameters, however this is not recommended as it can lead to instability. Instead we provide hold_canvas....."

:+1: looks good to me. Maybe we can mention the `iopub_msg_rate_limit` option? So people can look for it if they really want it?

> Also: What does "`hold_canvas` must be used without moderation" mean?

It means it should be used as much as possible, it's better to use it excessively than not use it at all. I am in favor of rephrasing this if you think it's not clear.

**Comment by ianhi** [comment]
> Maybe we can mention the iopub_msg_rate_limit option?

What about just linking to this issue? "can increase this limit via internal Jupyter parameters (see <link>) ..."


>  I am in favor of rephrasing this if you think it's not clear.

I think that "must" is what threw me off the most. Just tacking on your explanation to the previous paragraph and removing the "must be used.." would make it pretty clear.

"We provide a `hold_canvas` context manager which allows you to hold all the commands and send them in a single batch at the end. You should try to use `hold_canvas` as much as possible for optimal performance."

**Comment by martinRenou** [comment]
I am all in favor of what you are suggesting. Would you like to open a PR? So you get credits for what your suggestions.

**Comment by ianhi** [comment]
:+1:

**Comment by martinRenou** [comment]
Closing as fixed by your PR
