### ISSUE TITLE
image_data Serialization

### ISSUE THREAD

**Issue by ianhi** [martinRenou/ipycanvas#104]
The setup you currently have for image serialization works so I don't think there's a strong reason to change it, but I figured out a simpler serialization scheme from `canvas` -> `numpy array` that I think would allow you to drop the Pillow dependency if you wanted and would reduce the complexity of `toBytes` in `util.ts`. Figured I ought to share in case its helpful given how much looking at your source code has helped me.

**`toBytes`**
To get the bytes from a canvas you currently do this
https://github.com/martinRenou/ipycanvas/blob/09ca4e04c3c43bca5df46975cad28ada3d50750e/src/widget.ts#L311
https://github.com/martinRenou/ipycanvas/blob/09ca4e04c3c43bca5df46975cad28ada3d50750e/src/utils.ts#L101-L117
I think you could instead just do
```typescript
const bytes = this.ctx.getImageData(
      0,
      0,
      this.canvas.width,
      this.canvas.height
    ).data.buffer;
```
though I found it nice to also include hte width and height in what I pass back to python ([ref](https://github.com/ianhi/ipysegment/blob/5b57d8c83bca79f40d3f1949420fb63642bba4f5/src/widget.ts#L18))
`return { width: image.width, height: image.height, data: new DataView(image.data.buffer) };`

then on the python side to get the numpy array without PIL the deserializer looks like ([example](https://github.com/ianhi/ipysegment/blob/5b57d8c83bca79f40d3f1949420fb63642bba4f5/ipysegment/segment.py#L21))
```python
_bytes = None if json['data'] is None else json['data'].tobytes()
return  np.copy(np.frombuffer(_bytes, dtype=np.uint8).reshape(json['width'], json['height'],  4))
```

the first line is just the function that gets used byteserialization in ipywidgets and the `copy` is separate the memory from that used by javascript and thus make it a writeable array.

Though I think an even more general solution is to use the serializers and traittypes from https://github.com/vidartf/ipydatawidgets which allow `image_data` to just be directly set and accessed as numpy arrays. For example this widget which displays a 2D RGBA image based on numpy arrays https://github.com/vidartf/ipydatawidgets/blob/master/ipydatawidgets/ndarray/media.py

----
I hope this is helpful! If this isn't then no worries and feel free to close this.

**Comment by martinRenou** [comment]
Thanks for opening an issue!

I am surprised I did not use `this.ctx.getImageData` in the first place. I hope I did not have a good reason to do not so. I totally agree with your implementation, if you can come up with a PR I would be happy to merge it! Also removing the Pillow dependency is good.

> Though I think an even more general solution is to use the serializers and traittypes from https://github.com/vidartf/ipydatawidgets

I disagree with this. I don't want to depend on another widgets library. Having users to install one labextension/nbextension is already quite difficult, so asking them to install two of them in order for ipycanvas to work is too much IMO.

**Comment by martinRenou** [comment]
It would be nice to compare performances between your solution and the previous one though. I might have used the `toBlob` for performances purpose, but I am not sure.

**Comment by ianhi** [comment]
> I disagree with this. I don't want to depend on another widgets library. Having users to install one labextension/nbextension is already quite difficult, so asking them to install two of them in order for ipycanvas to work is too much IMO.

100% that installing more than one labextension is no good. Though I don't think that would be necessary. It's not clear from the name but that is broken into separate packages so you can have the traittype and serializers without requiring any `jupyter labextension install` steps. There is 1 python package and two different js packages. 1 of them is the extension and widgets, and the other is just the serializers. (related is this issue https://github.com/jupyter-widgets/traittypes/issues/21)


> It would be nice to compare performances between your solution and the previous one though. I might have used the toBlob for performances purpose, but I am not sure.


Maybe size was your reason? see: https://stackoverflow.com/a/34924715/835607. given the differences in size maybe it's best to leave as is?

 I think that the ndarray traittype gets around by offering a compression option https://github.com/vidartf/ipydatawidgets/blob/69eebeb5647d58dec6bf459d424727cb23cce8ab/packages/serializers/src/ndarray.ts#L167

**Comment by ianhi** [comment]
Is performance also the reason you have `sync_image_data` default to False?

**Comment by martinRenou** [comment]
> Though I don't think that would be necessary. It's not clear from the name but that is broken into separate packages so you can have the traittype and serializers without requiring any jupyter labextension install steps. There is 1 python package and two different js packages. 1 of them is the extension and widgets, and the other is just the serializers. (related is this issue jupyter-widgets/traittypes#21)

Good catch! Then I agree we could depend on the Python package to make things modular :) 

> Maybe size was your reason? see: https://stackoverflow.com/a/34924715/835607. given the differences in size maybe it's best to leave as is?

Yes that might have been the reason for not using `getImageData` directly. Although if you think the compression that happens during the blob transformation is a problem (loss of data?) we should maybe consider using `getImageData` instead.

> Is performance also the reason you have sync_image_data default to False?

Indeed.

**Comment by martinRenou** [comment]
> Is performance also the reason you have sync_image_data default to False?

I might be wrong, but I thought that in most of the cases, people would not need to retrieve the image as a NumPy array.

**Comment by ianhi** [comment]
>  Although if you think the compression that happens during the blob transformation is a problem (loss of data?) we should maybe consider using `getImageData` instead

I think PNG compression is lossless and the conversions that you're using result in PNG compression so that shouldn't be an issue. If you wanted an intermediate to using ipydatawidgets then you can trade the Pillow dep for a typescript one ([pako](https://www.npmjs.com/package/pako)) (like this https://github.com/ianhi/ipysegment/commit/0127f5b9c71defc09201a093a8d511df62a771ba) and use the python builtin `zlib`. So I guess in the end it's kind of a wash.

> I might be wrong, but I thought that in most of the cases, people would not need to retrieve the image as a NumPy array.

That also rings true

**Comment by martinRenou** [comment]
Should we close this?

**Comment by ianhi** [comment]
Probably. Feel free to re-open if you ever want to change your image data serialization strategy, but what you have now works, so there's no real need to change it.
