### ISSUE TITLE
Linking with ipywidgets

### ISSUE THREAD

**Issue by Dommsko** [martinRenou/ipycanvas#107]
Hey there,

I really like to work with ipycanvas and built a basic structure for my project that I would like to animate interactively using ipywidgets. However, I did not figure out yet how to link for example a slider to affect let's say an angle of rotation inside my canvas. Is this natively possible and I just didn't figure it out yet? Or would I have to go through the whole JavaScript custom widget tutorial? I don't know JS and would not be able to use Jupyter Lab which would be a shame :-/
I already tried to create my own "animation engine" but only got choppy results so far. Some things which work in native Python don't seem to work fine inside of Jupyter (in particular threads and timers).

Kind regards,
Domme

**Comment by martinRenou** [comment]
Hey!

Can you share your code? So that I can help you improve it if I can :)

> I already tried to create my own "animation engine" but only got choppy results so far

Use `hold_canvas` as much as possible, that should improve the performances in your animation.

> Is this natively possible and I just didn't figure it out yet? Or would I have to go through the whole JavaScript custom widget tutorial?

No need to write a single line of JavaScript :) You should be able to do something like:

```python
from ipywidgets import IntSlider
from ipycanvas import Canvas, hold_canvas

# Create your canvas
# my_canvas = ...

angle_slider = IntSlider(min=0, max=90)

def update_line_angle(change):
    with hold_canvas(my_canvas):
        my_canvas.clear()
        
        new_angle = change['new']

        # Draw here the line given the new angle (new value of the slider)

# Observe the slider value and call update_line_angle whenever it changes
angle_slider(update_line_angle, 'value')
```

**Comment by Dommsko** [comment]
Hi,

thanks for your fast reply! I knew there had to be some trick ;) I already discarded my own animation attempts, but I will now try to implement it using your approach.

Regards,
Domme

**Comment by martinRenou** [comment]
There was an issue in the code I provided, I just updated it :)

**Comment by martinRenou** [comment]
Closing as solved, but don't hesitate to ask more questions here.
