### ISSUE TITLE
Automatic scaling of a canvas

### ISSUE THREAD

**Issue by Dommsko** [martinRenou/ipycanvas#110]
Hello,

I am really having fun learning ipycanvas. However, now that I get more serious about my projects I am beginning to wonder if there is an easy way to automatically scale a canvas to the available size. For example when I resize the browser window or when I am using a phone to display my notebook it should automatically increase/decrease the size accordingly.

Kind Regards,
Domme

**Comment by martinRenou** [comment]
Hi!

Yes it is part of the plan. I'd like to work on this this week-end when I find a couple of hours free. I'd like this to be introduced for the next release.

**Comment by Dommsko** [comment]
Hi Martin,

thanks for the fast reply. That's great to hear! It means that I can focus on creating more content instead. Have a nice weekend!

Kind Regards,
Domme

**Comment by Dommsko** [comment]
Hi Martin,

thanks for the fast reply. That's great to hear! It means that I can focus on creating more content instead. Have a great weekend!

Regards,
Domme

**Comment by martinRenou** [comment]
This has been implemented in #111 and #113.

You will soon be able to do:
```python
canvas.layout.width = '100%'
canvas.layout.height = 'auto'
```
to get a "responsive" canvas which takes as much space as available while respecting the aspect ratio.

**Comment by Dommsko** [comment]
Wow, that was fast! Thanks for all of your efforts.
