### ISSUE TITLE
MultiCanvas does not receive events in ipycanvas 0.5.0?

### ISSUE THREAD

**Issue by cloudrickT** [martinRenou/ipycanvas#117]
I think MultiCanvas does not receive events in ipycanvas 0.5.0 using the built-in mouse events.

Tried with the example notebook in JupyterLab:
https://github.com/martinRenou/ipycanvas/blob/master/examples/hand_drawing.ipynb

And in binder:
https://mybinder.org/v2/gh/martinRenou/ipycanvas/stable?filepath=examples

The interaction_layer is able to receive events by displaying the individual layer.
But by displaying the actual MultiCanvas, the interaction_layer does not receive events.

For now, downgrading to 0.4.7 works
conda install ipycanvas=0.4.7 --no-channel-priority
jupyter labextension install ipycanvas@0.4.7

**Comment by FredKellerman** [comment]
Hi and thank you for this wonderful work!  I was just about to report something similar.  I use this with 2 different platforms.  Both Xilinx Zynq SoC, one 64-bit the other 32-bit.  I use the same code on both.

64-bit works perfect but on the 32-bit platform (arm7l, 4.14.0, Jupyter Lab 1.1.3, ipycanvas=.5) no mouse events are received back to Python when using  multi-canvas.  Single canvas seems to be fine.  I have not tried earlier versions of ipycanvas to see if it fixes it.

Is this the same issue or should I create a new one?

**Comment by martinRenou** [comment]
Yes I suppose it's the same issue. There have been big design changes in MultiCanvas from 0.4.7 to 0.5, which totally broke events for it. I suggest keeping 0.4.7 for now, I'll come up with a fix as soon as possible.

**Comment by martinRenou** [comment]
This PR #118 should fix it (by removing code :smile:)

**Comment by martinRenou** [comment]
Released in 0.5.1
