### ISSUE TITLE
hand_drawing not working on Binder

### ISSUE THREAD

**Issue by athewsey** [martinRenou/ipycanvas#120]
If I understand the intent of the `hand_drawing` sample correctly, the user should be able to draw over the top of the background image with the stroke width and colour selected in the widgets, right?

For me the widget loads and colour/stroke width selection works, but click/drag doesn't seem to do anything... On both Firefox 68.8 ESR and Chrome 85.0. Using Mac OSX 64 bit and plain Jupyter (not JupyterLab) in Binder.

I'm searching for a solution that will allow collecting a hand drawn sketch in JupyterLab and exporting to an image or NumPy array... Which it seems like ipycanvas might support?

**Comment by martinRenou** [comment]
The Binder was building ipycanvas `0.5.0` which had issues with mouse events on the MultiCanvas class (breaking this example). I just updated the binder link to use `0.5.1`, it should fix it.

**Comment by martinRenou** [comment]
Actually ipycanvas `0.5.1` is not on anaconda.org yet. It should be uploaded today.

**Comment by martinRenou** [comment]
Fixed, see https://mybinder.org/v2/gh/martinRenou/ipycanvas/stable?filepath=examples
