### ISSUE TITLE
Version: 0.5.1 MultiCanvas mouse event still not work

### ISSUE THREAD

**Issue by Bookaa** [martinRenou/ipycanvas#121]
Version: 0.5.1 MultiCanvas mouse event still not work

**Comment by martinRenou** [comment]
It does, you can check it on the Binder:  https://mybinder.org/v2/gh/martinRenou/ipycanvas/stable?filepath=examples

Can you tell me how you updated ipycanvas?

**Comment by Bookaa** [comment]
I find I made a mistake. Everything is OK now.

I install 0.5.0, open a .pynb page, and it get a mouse event error. I stop the jupyter notebook server, reinstall 0.5.1. run the jupyter notebook server. and then in my explore, find this page, click restart server. I think everything will be new. But it did not! the error keep there.  Now I close the page and open it again, everything is OK now.  so weird!

sorry for disturbing

**Comment by martinRenou** [comment]
No worries!

> Now I close the page and open it again

Yes, this was needed in order to reload the new JavaScript package in the page.
