### ISSUE TITLE
Output Widget on Canvas Layer

### ISSUE THREAD

**Issue by GowthamiCherukuri** [martinRenou/ipycanvas#122]
Is there any way to add output widget on the canvas layer. 
For example, if I create multicanvas with 2 layers, when I click on particular portion of the canvas, a python function runs in the background. So I want to show the result on the top layer of the canvas similar to what output widget does in ipywidgets. 
Or Is there any way to add the ipywidgets on the canvas layer instead of creating at the bottom of the canvas.

**Comment by martinRenou** [comment]
Hey! Not sure there is a way to put an Output widget on top of a Canvas,  but even if there was you would not see your canvas anymore and click events would not work.

There this code snippet here that prints stuffs on the canvas, maybe you could reuse it: https://github.com/martinRenou/ipycanvas/issues/61#issuecomment-626127902
