### ISSUE TITLE
JupyterLab Error displaying widget: model not found

### ISSUE THREAD

**Issue by gkvoelkl** [martinRenou/ipycanvas#131]
Hello 

I installed ipycanvas in JupyterLab and got the message 'Error displaying widget: model not found'

In developer console I found

Error: Module ipycanvas, semver range ^0.6.1 is not registered as a widget module

Does anyone know what went wrong?

Thanks

**Comment by martinRenou** [comment]
Hello,

Can you run `jupyter labextension list` and show me the output?
Also, which JupyterLab version do you use?

And did you run `jupyter labextension install @jupyter-widgets/jupyterlab-manager ipycanvas` when doing the installation?

**Comment by gkvoelkl** [comment]
The result of `jupyter labextension list`:

`JupyterLab v2.2.6
Known labextensions:
   app dir: /Users/user/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyter-widgets/jupyterlab-sidecar v0.5.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        ipycanvas v0.6.1  enabled  OK
        ipyevents v1.8.1  enabled  OK

Uninstalled core extensions:
    bqplot
    ipycanvas
    ipyevents
    ipygany
    jupyter-matplotlib
    keplergl-jupyter`

And I did run the jupyter labextension install .. statement

**Comment by martinRenou** [comment]
Do you have core widgets working?

```python
from ipywidgets import IntSlider

IntSlider()
```

I suspect something broken with your environment, let me suggest to start again from a clean env with only ipycanvas installed, see if ipycanvas is really the culprit.

**Comment by martinRenou** [comment]
Could you make it work in the end?

I am closing this issue, as it is more likely a broken installation and nothing can be done in ipycanvas to fix it. Note that JupyterLab 3 is coming, and it will be much easier for people to get a working installation with JupyterLab 3 and ipycanvas.

**Comment by gkvoelkl** [comment]
In Jupyter Notebook all worked well.

Only JupyterLab does not work.

After I uninstalled Jupyter and all components and all config files and installed all again, all works.

Thanks
