### ISSUE TITLE
JupyterLab 3 error

### ISSUE THREAD

**Issue by dsblank** [martinRenou/ipycanvas#146]
Great project! I was just sitting down to write something like this. It looks fantastic, and takes care of the details to make this a great foundation.

I presume that this error is because ipycanvas does not yet support JupyterLab 3:

![Screenshot from 2020-12-12 07-29-19](https://user-images.githubusercontent.com/168568/101988003-f2e15700-3c4b-11eb-81fd-0e9c6e2f6e7e.png)

Testing on:

* Python 3.9
* jupyterlab==3.0.0.rc13

Let me know if there is anything I can help with.

**Comment by martinRenou** [comment]
> Great project! I was just sitting down to write something like this. It looks fantastic, and takes care of the details to make this a great foundation.

Thanks for the kind words 😳 

Indeed it does not yet support JupyterLab 3, as soon as JupyterLab 3 is out I'll make a release of ipycanvas supporting it :)

**Comment by stromnov** [comment]
JupyterLab 3.0.0 is out! :) (https://github.com/jupyterlab/jupyterlab/tree/v3.0.0)

**Comment by martinRenou** [comment]
We'll need to wait for ipywidgets to update as well
