### ISSUE TITLE
Question: how to tell if canvas is connected?

### ISSUE THREAD

**Issue by dsblank** [martinRenou/ipycanvas#147]
This may be a question for `ipylab` but it may require some low-level canvas API:

I'm trying to make some start-up code that will add a canvas in a panel using ipylab:

```python
app = JupyterFrontEnd()

panel = None
for widget in app.shell.widgets.values():
    if hasattr(widget, "title") and widget.title.label == "TITLE":
        panel = widget
        break
        
if panel is None:
    panel = Panel()
    panel.children = [canvas]
    panel.title.label = "TITLE" 
    app.shell.add(panel, 'main', {'mode': 'split-right'})
else:
    panel.children = [canvas]
```

where canvas is my ipycanvas canvas.

The problem is that in JupyterLab, the panel is in the app.shell.widgets, but it is no longer "connected" in HTML dom language if the panel has been closed. Is there a way to get to the HTML canvas element "isConnected" via ipywidgets, or ipycanvas, even if the panel has been closed?

**Comment by martinRenou** [comment]
Adding @jtpio to this discussion who might know the answer 😊

**Comment by dsblank** [comment]
For now, it looks like ipylab objects persist. I'll ask over there. Thanks!

**Comment by jtpio** [comment]
Ah I forgot to reply here!

> for widget in app.shell.widgets.values():

Normally `app.shell.widgets` is not part of the public API yet. Or you meant accessing the "private" `_widgets property?

**Comment by dsblank** [comment]
No, it was `app.shell.widgets` but I'll ask some follow up questions over on ipylab.

![Screenshot from 2020-12-17 14-51-15](https://user-images.githubusercontent.com/168568/102553285-80231200-4077-11eb-916d-aef987d54b5c.png)
