### ISSUE TITLE
Circle radius differs from Canvas to RoughCanvas

### ISSUE THREAD

**Issue by deeplook** [martinRenou/ipycanvas#160]
One would expect "roughly" (sic!) the same output, but no. With `RoughCanvas`being a subclass of `Canvas` this is a bit puzzling.

```python
from ipycanvas import Canvas, RoughCanvas
from ipywidgets import HBox

p = (100, 100)
q = (200, 200)
radius = 100
size = 300

canv = Canvas(width=size, height=size)
canv.stroke_rect(0, 0, size, size)
canv.stroke_circle(*p, radius)
canv.stroke_circle(*q, radius)

r_canv = RoughCanvas(width=size, height=size)
r_canv.stroke_rect(0, 0, size, size)
r_canv.stroke_circle(*p, radius)
r_canv.stroke_circle(*q, radius)

HBox([canv, r_canv])
```

<img width="609" alt="Screenshot 2020-12-21 at 19 19 20" src="https://user-images.githubusercontent.com/1001778/102809446-4b3df480-43c2-11eb-84e9-a0841029fe4e.png">

**Comment by martinRenou** [comment]
Thanks for reporting!

Indeed it looks like the RoughCanvas circle radius is completely off
