### ISSUE TITLE
Canvas not showing in notebooks and giving model not found error in JupyterLab

### ISSUE THREAD

**Issue by InfantLab** [martinRenou/ipycanvas#161]
Hi Martin,

I  have the same as issue #131. ipycanvas has stopped working on my machine. in JupyterLab and i get the message  `Error displaying widget: model not found`. 

In notebooks there is no error but the canvas never displays. And in the web developer console I get a js error. `Uncaught (in promise) Unknown dtype undefined`

`ipwidgets` and `matplotlib` are both working fine. I set up a completely new environment and still have the problem. 

Any idea what is wrong? Or what else I could try?

Thanks,
Caspar

my `jupyter labextension list` gives 
```
JupyterLab v2.2.6
Known labextensions:
   app dir: C:\Users\cas\Anaconda3\envs\vasc\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  ok
        ipycanvas v0.8.0 enabled  ok
        jupyter-matplotlib v0.7.4 enabled  ok
        jupyterlab-jupytext v1.2.3 enabled  ok
```

**Comment by martinRenou** [comment]
Hi!

Could you please show the output of `conda list | grep ipycanvas`?

And `jupyter nbextension list`?

**Comment by InfantLab** [comment]
Thanks Martin,
Those commands show:
`conda list | Select-String -Pattern ipycanvas`
```
ipycanvas                 0.8.0              pyhd8ed1ab_0    conda-forge
```
`jupyter nbextension list`
```
Known nbextensions:
  config dir: C:\Users\cas\.jupyter\nbconfig
    notebook section
      nbextensions_configurator/config_menu/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
  config dir: C:\Users\cas\Anaconda3\envs\vasc\etc\jupyter\nbconfig
    notebook section
      ipycanvas/extension enabled
      - Validating: ok
      jupyter-matplotlib/extension enabled
      - Validating: ok
      jupytext/index enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok
      nbextensions_configurator/config_menu/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
```

Curiously, when i looked at the ipycanvas version in my 'base' environment, the ipycanvas was version 0.4.3
`conda list | Select-String -Pattern ipycanvas`
```
ipycanvas                 0.4.3                      py_0    conda-forge
```

When i updated that version, `ipycanvas` started working on other environment too. (Which is weird, I thought `conda` environments were all independent of each other?)

Anyway, that's solved it.
Thanks, for the speedy response

**Comment by martinRenou** [comment]
IIRC if a parent environment contains a package it will be available in the child environment. It's better to not install anything in base, or keep the bare minimum.

**Comment by romanov-o** [comment]
@martinRenou, same issue with my JupyterLab and ipycanvas v0.8.2
```
$conda list | grep ipycanvas
ipycanvas                 0.8.2              pyhd8ed1ab_0    conda-forge
$ jupyter nbextension list
Known nbextensions:
  config dir: /Users/alex/opt/anaconda3/etc/jupyter/nbconfig
    notebook section
      ipycanvas/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

**Comment by martinRenou** [comment]
Could you run `jupyter labextension list`?

**Comment by romanov-o** [comment]
```
$ jupyter labextension list
JupyterLab v3.0.15
/Users/alex/opt/anaconda3/share/jupyter/labextensions
        ipycanvas v0.8.2 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /Users/alex/opt/anaconda3/share/jupyter/lab
        @bokeh/jupyter_bokeh v3.0.0 enabled OK


Uninstalled core extensions:
    @bokeh/jupyter_bokeh
```

**Comment by martinRenou** [comment]
Can you try opening your browser dev tools when in JupyterLab, and report any error you see?

**Comment by romanov-o** [comment]
'''
Plugin 'ipycanvas:plugin' failed to activate.
(anonymous) @ index.es6.js:282
index.es6.js:283 Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    at W.e.resolveRequiredService (index.es6.js:197)
    at index.es6.js:155
    at Array.map (<anonymous>)
    at W.e.activatePlugin (index.es6.js:155)
    at index.es6.js:281
    at Array.map (<anonymous>)
    at W.e.start (index.es6.js:280)
    at Y (index.out.js:615)
(anonymous) @ index.es6.js:283
3523.fa256ee012d38a89b65a.js:1 Error: widget model not found
    at x.get_model (523.fa256ee012d38a89b65a.js:1)
    at u.renderModel (523.fa256ee012d38a89b65a.js:1)
renderModel @ 523.fa256ee012d38a89b65a.js:1
272.2a8425db7209008188fc.js:1 Could not instantiate widget
(anonymous) @ 272.2a8425db7209008188fc.js:1
272.2a8425db7209008188fc.js:1 Error: Could not create a model.
    at 272.2a8425db7209008188fc.js:1
    at async _handleCommOpen (523.fa256ee012d38a89b65a.js:1)
    at async C._handleCommOpen (default.js:1020)
    at async C._handleMessage (default.js:1188)
(anonymous) @ 272.2a8425db7209008188fc.js:1
default.js:1027 Exception opening new comm
_handleCommOpen @ default.js:1027
2523.fa256ee012d38a89b65a.js:1 Uncaught (in promise) Error: Module ipycanvas, semver range ^0.8.2 is not registered as a widget module
    at x.loadClass (523.fa256ee012d38a89b65a.js:1)
    at x.<anonymous> (272.2a8425db7209008188fc.js:1)
    at 272.2a8425db7209008188fc.js:1
    at Object.next (272.2a8425db7209008188fc.js:1)
    at 272.2a8425db7209008188fc.js:1
    at new Promise (<anonymous>)
    at S (272.2a8425db7209008188fc.js:1)
    at x.e._make_model (272.2a8425db7209008188fc.js:1)
    at x.<anonymous> (272.2a8425db7209008188fc.js:1)
    at 272.2a8425db7209008188fc.js:1
523.fa256ee012d38a89b65a.js:1 Error: Module ipycanvas, semver range ^0.8.2 is not registered as a widget module
    at x.loadClass (523.fa256ee012d38a89b65a.js:1)
    at x.<anonymous> (272.2a8425db7209008188fc.js:1)
    at 272.2a8425db7209008188fc.js:1
    at Object.next (272.2a8425db7209008188fc.js:1)
    at 272.2a8425db7209008188fc.js:1
    at new Promise (<anonymous>)
    at S (272.2a8425db7209008188fc.js:1)
    at x.e._make_model (272.2a8425db7209008188fc.js:1)
    at x.<anonymous> (272.2a8425db7209008188fc.js:1)
    at 272.2a8425db7209008188fc.js:1
renderModel @ 523.fa256ee012d38a89b65a.js:1
'''

**Comment by martinRenou** [comment]
Thanks.

Could you try one last thing? Can you try uninstalling `@bokeh/jupyter_bokeh` and reinstall `@jupyter-widgets/jupyterlab-manager` and `ipycanvas`? I suspect `@bokeh/jupyter_bokeh` could be the culprit.

**Comment by romanov-o** [comment]
You were right. I've uninstalled `@bokeh/jupyter_bokeh` and `ipycanvas` is working fine now!
