### ISSUE TITLE
Javascript error after installing ipycanvas on Mac

### ISSUE THREAD

**Issue by caranha** [martinRenou/ipycanvas#177]
Hello!

I'm having a problem with running ipycanvas on some environments. After installing ipycanvas from inside jupyter notebook with `!pip install ipycanvas`, and running a simple test code (create a 20x20 empty canvas and display it), nothing shows up, but no error messages come up. Investigating it, I noticed that the javascript console is throwing a lot of errors, but I could not understand from these errors what (if anything) is missing.

Environment: MacOS 10, Chrome / Safari
pip verison 19.1.1
jupyter 1.0.0 (client 5.3.1, core 4.5.0, jupyterlab 1.0.2, jupyterlab-widgets 1.0.0)

Javascript errors: [error.txt](https://github.com/martinRenou/ipycanvas/files/5846320/error.txt)

By the way, the same code worked without a problem on an Ubuntu 20 environment with Firefox, so I'm guessing there is some package that is not being installed correctly when I pip install ipycanvas in the mac, but I can't figure out what is missing. 

Any help is appreciated! Let me know if I can provide any extra info.

**Comment by martinRenou** [comment]
Hello!

Could you please run the following command:
```
jupyter labextension list
```

And:
```
pip list | grep ipycanvas
```

**Comment by caranha** [comment]
% jupyter labextension list
Traceback (most recent call last):
  File "/usr/local/bin/jupyter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/jupyter_core/command.py",
line 285, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/local/lib/python3.9/site-packages/jupyter_core/command.py",
line 124, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-labextension` not found.
% pip3 list | grep ipycanvas
ipycanvas           0.8.2

**Comment by martinRenou** [comment]
Are you actually using JupyterLab?

The `jupyter labextension` command failed, and it looks like jupyterlab is not installed.

**Comment by caranha** [comment]
I know. I also found it super weird.

Yes, I'm using jupyter lab. By the way, I tested the same command on
an ubuntu environment where ipycanvas is working OK, and I also get an
error when trying the labextension command:

```
caranha@Capybara:~$ jupyter labextension list
pyenv: jupyter-labextension: command not found
```

**Comment by martinRenou** [comment]
What kind of setup do you have? Do you use a tool for virtual environments?

I really recommend using miniconda and starting using conda environments. It's the more robust solution.

Can you run 
```
which jupyter
```

And
```
jupyter lab path
```

And 
```
jupyter --path
```
