### ISSUE TITLE
I can't get see the canvas :(, got an error in console.

### ISSUE THREAD

**Issue by anandvsr** [martinRenou/ipycanvas#180]
`vendors~main.d6ae31c7fff1f92f0bb6.js:2 Exception opening new comm
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
(anonymous) @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
Promise.then (async)
_onWSMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
vendors~main.d6ae31c7fff1f92f0bb6.js:2 Exception opening new comm
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
(anonymous) @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
Promise.then (async)
_onWSMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
vendors~main.d6ae31c7fff1f92f0bb6.js:2 Exception opening new comm
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
(anonymous) @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
Promise.then (async)
_onWSMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
vendors~main.d6ae31c7fff1f92f0bb6.js:2 Exception opening new comm
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
(anonymous) @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
Promise.then (async)
_onWSMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
vendors~main.d6ae31c7fff1f92f0bb6.js:2 Exception opening new comm
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
(anonymous) @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
Promise.then (async)
_onWSMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
vendors~main.d6ae31c7fff1f92f0bb6.js:2 Exception opening new comm
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
(anonymous) @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
Promise.then (async)
_onWSMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
vendors~main.d6ae31c7fff1f92f0bb6.js:2 Exception opening new comm
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleCommOpen @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
async function (async)
_handleMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
(anonymous) @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
Promise.then (async)
_onWSMessage @ vendors~main.d6ae31c7fff1f92f0bb6.js:2
`

![Screenshot from 2021-02-05 16-17-51](https://user-images.githubusercontent.com/66105422/107024329-edc50200-67cd-11eb-964a-a3f321a473db.png)
 Using Jupyter lab, version is 2.2.6

Sorce from: https://github.com/martinRenou/ipycanvas/blob/master/examples/hand_drawing.ipynb

**Comment by martinRenou** [comment]
What does `jupyter labextension list` give you?

**Comment by martinRenou** [comment]
It seems to me, looking at your screenshot, that ipywidgets also does not work in your setup.

**Comment by anandvsr** [comment]
> What does `jupyter labextension list` give you?

![Screenshot (3)](https://user-images.githubusercontent.com/66105422/107175941-11699180-69f4-11eb-91fd-41101a7a3275.png)

**Comment by anandvsr** [comment]
`jupyter labextension install @jupyter-widgets/jupyterlab-manager ipycanvas`
Sorry for this. I didn't install the lab extension. Now it's worked. :+1:

**Comment by martinRenou** [comment]
Nice!
