### ISSUE TITLE
missing dependency `jupyterlab-manager`

### ISSUE THREAD

**Issue by goekce** [martinRenou/ipycanvas#187]
dear @martinRenou I noticed that `ipycanvas` does not work without `jupyterlab_widgets`, but `jupyterlab_widgets` is not listed in `setup.py` as a dependency:

https://github.com/martinRenou/ipycanvas/blob/30ccca2a7cae2ead7840ea391e3a7f7fde44a73a/setup.py#L96-L101

does `setup.py` not support jupyterlab related deps?

**Comment by martinRenou** [comment]
Hello :)

`jupyterlab_widgets` is a dependency of `ipywidgets`, see https://github.com/jupyter-widgets/ipywidgets/blob/master/setup.cfg#L43 so everything should be fine.
