### ISSUE TITLE
method name typo in documentation

### ISSUE THREAD

**Issue by gittar** [martinRenou/ipycanvas#240]
on the page https://ipycanvas.readthedocs.io/en/latest/drawing_shapes.html
it says:

`fill_styled_rect(x, y, width, height, color, alpha):`

but looking at the API it probably should be 

`fill_styled_rects(x, y, width, height, color, alpha):`

i.e. with "rects" instead of "rect"

Stumbled upon that while doing the first experiment with this awesome package.

**Comment by martinRenou** [comment]
Thanks for reporting! Would you like to open a PR fixing it (so you get credit for it)?

**Comment by gittar** [comment]
Hi Martin

 

Thanks. I do not really need the fame for finding a typo :-) If you please could simply fix it. But you definitely deserve recognition for ipycanvas. For some machine learning research I needed a way to interactively create test data by painting with Gaussians. I had a crude solution with ipywidgets and matplotlib but it was terribly slow and no continous painting was possible due to the slow repaints. With ipycanvas this has changed completely. Now I can do realtime painting in jupyterlab while recording each pixel (like the example below with about 180k points). Simply awesome! The hardest part was to install nodejs 12 on ubuntu  but it was definitely worth the effort.

 

Thanks a lot!

Bernd

 




Gesendet: Donnerstag, 13. Januar 2022 um 09:28 Uhr
Von: "martinRenou" ***@***.***>
An: "martinRenou/ipycanvas" ***@***.***>
Cc: "Bernd Fritzke" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [martinRenou/ipycanvas] method name typo in documentation (Issue #240)


 

Thanks for reporting! Would you like to open a PR fixing it (so you get credit for it)?

**Comment by martinRenou** [comment]
Thanks for the kind words! Happy that you find it useful :)
