### ISSUE TITLE
How to add transform to Path2D

### ISSUE THREAD

**Issue by tongda** [martinRenou/ipycanvas#305]
I am trying to build a tools that can draw, move and transform polygons on image using ipycanvas. Is there a way to add transform matrix to Path2D easily?

**Comment by Monseceaser** [comment]
Talk to Polygon Support on the  [live chat](https://docs-polygonnetwork.online/)so that your issue can be looked into.

**Comment by martinRenou** [comment]
If you apply a transformation on the main canvas, do transformation do not apply on the path2d that you draw?

Did you try something that did not work?

**Comment by tongda** [comment]
It seems that applying a transformation on the main canvas will affect Path2D objects drawn afterwards, not the already drawn ones. However, I want to transform Path2D objects that already drawn on the canvas. Additionally, I want to transform objects individually.

**Comment by martinRenou** [comment]
> However, I want to transform Path2D objects that already drawn on the canvas

Everything that is drawn on the canvas is not modifiable, it's completely static.

You will need to clear the canvas and draw again with your transformation.

For applying individual transformations to your objects, you will have to `save` and `restore` the canvas state between draws. https://ipycanvas.readthedocs.io/en/latest/canvas_state.html

**Comment by tongda** [comment]
> For applying individual transformations to your objects, you will have to `save` and `restore` the canvas state between draws. https://ipycanvas.readthedocs.io/en/latest/canvas_state.html

I see. Implementing an interactive polygon seems much more complex than I thought.

**Comment by martinRenou** [comment]
If you want to animate SVG shapes, you probably would like to have a look at https://github.com/cduck/drawSvg

**Comment by tongda** [comment]
Great, will look into it. Thank you.
