### ISSUE TITLE
voila fails to load ipycanvas.js from localhost

### ISSUE THREAD

**Issue by tongda** [martinRenou/ipycanvas#307]
Lib versions:
voila: 0.4.0
ipywidgets: 8.0.2
ipycanvas: 0.13.1

When rendering .ipynb with voila, in browser console, there is always an error as follows:

```
require.min.js:1          GET http://10.168.1.150:8800/voila/ipycanvas.js net::ERR_ABORTED 404 (Not Found)
Falling back to https://cdn.jsdelivr.net/npm/ for ipycanvas@^0.13
```

How can I work around this and let voila load ipycanvas js from local instead of CDN?

**Comment by martinRenou** [comment]
You need to use the `--enable_nbextensions=True` option for Voila.

You should know that there are some limitations in Voila: https://ipycanvas.readthedocs.io/en/latest/advanced.html#ipycanvas-in-voila

**Comment by tongda** [comment]
Thanks.

> You need to use the `--enable_nbextensions=True` option for Voila.

This solve the problem and console log with `Loaded classic notebook extension "ipycanvas/extension".`. Great.

> You should know that there are some limitations in Voila: https://ipycanvas.readthedocs.io/en/latest/advanced.html#ipycanvas-in-voila

Well... I've already encountered the problem. I did not notice that chapter at first.
