### ISSUE TITLE
bundle text and shape into one object

### ISSUE THREAD

**Issue by bhomass** [martinRenou/ipycanvas#310]
can we bundle a shape like a rectangle with a few lines of text inside, just like how you would group elements together in powerpoint?

**Comment by martinRenou** [comment]
You could draw your rectangle and text on a separate canvas that you don't display on the screen, and then draw this separate canvas on your main canvas. Maybe that would fit your needs?

**Comment by bhomass** [comment]
Hi thanks, I can't find a direct api call to paint a member canvas to the main canvas. which method do you suggest?

**Comment by martinRenou** [comment]
You can draw a canvas on another one with `draw_image` https://ipycanvas.readthedocs.io/en/latest/drawing_images.html?highlight=draw_image#from-another-canvas

**Comment by bhomass** [comment]
thanks worked!
