### ISSUE TITLE
Take a screenshot of a drawing/canvas and save it?

### ISSUE THREAD

**Issue by haesleinhuepf** [martinRenou/ipycanvas#319]
Hi @martinRenou ,

ipycanvas is amazing! Just one quick question: Is it possible to retrieve a canvas in a numpy array or pillow image so that we can save a drawing?

Big thanks!

Best,
Robert

**Comment by martinRenou** [comment]
Thanks for the kind words!

You can retrieve the image following https://ipycanvas.readthedocs.io/en/latest/retrieve_images.html#get-image-data-as-a-numpy-array

Though it's indeed not an ideal API. I've been working on a more robust way to retrieve the image data in https://github.com/martinRenou/ipycanvas/pull/301 but it's not finished yet.

**Comment by haesleinhuepf** [comment]
Fantastic! Also for the instant reply!🤩
