### ISSUE TITLE
any way to pause animation?

### ISSUE THREAD

**Issue by bhomass** [martinRenou/ipycanvas#331]
Once the animation loop starts, there seems to be no way to pause it. I have button for setting a global pause flag, but the loop will run to the end before the flag gets set.

**Comment by martinRenou** [comment]
Thanks for opening an issue. The animation code is fully on your side, ipycanvas provides no mean to do animation, so you'll need to update your code to be able to pause your animation.

If you could share you for-loop code of your animation I could probably help.

**Comment by bhomass** [comment]
I found a way to do this using threads. Thanks
