### ISSUE TITLE
Canvas not scaled when the notebook is rendered with voila

### ISSUE THREAD

**Issue by benbovy** [martinRenou/ipycanvas#41]
Not sure if this is a `voila` or `ipycanvas` issue.

`Canvas.scale()` works fine in `notebook` or `jupyterlab` but not in `voila` rendered dashboards (the shaded image below should be larger):

<img width="486" alt="Screenshot 2019-10-16 at 08 59 50" src="https://user-images.githubusercontent.com/4160723/66896017-61009e80-eff4-11e9-9c1e-e944a49b8ace.png">

Also, when the voila dashboard is opened, the canvas is not visible (further action/draw makes it visible). Maybe it has something to do with the line below in the logs?

```
WARNING:tornado.general:403 GET /voila/files/voila/ipycanvas.js (::1): File not whitelisted
```

**Comment by benbovy** [comment]
To reproduce the issue: https://github.com/fastscape-lem/gilbert-board

**Comment by martinRenou** [comment]
Thanks for filling this issue! I'll give it a try. Are you running voila with `--enable_nbextensions=True`?

**Comment by benbovy** [comment]
> Are you running voila with --enable_nbextensions=True

Just tried it but no apparent effect.

**Comment by martinRenou** [comment]
It seems like the first commands are lost in the void... Never received by the Canvas. I will investigate a bit.

**Comment by martinRenou** [comment]
I think I've got a workaround for your scaled image. Every time you redraw the image, you should do something like:

```python
canvas.save()
canvas.scale(scale)
canvas.put_image_data(data, 0, 0)
canvas.restore()
```

And it should work.

But it does not fix the first render... I've got the feeling it can be a bug in the Voila widget manager, some comm messages that are not handled correctly when the widget is displayed.

**Comment by martinRenou** [comment]
The problem is actually that `ipycanvas` is almost stateless. And between the execution of the Notebook and the front-end initialization, some messages are sent and there is no Canvas view for receiving those messages...

I cannot think of a good way to tackle this issue right now. I can only think of ugly workarounds...

**Comment by benbovy** [comment]
> I cannot think of a good way to tackle this issue right now. I can only think of ugly workarounds...

Thanks for investigating anyway!

Regarding the 1st render, I guess I could add a code cell in the notebook (below the one that outputs the canvas) that triggers redrawing the canvas (that will be executed but hidden in the `voila` rendered dashboard).

**Comment by benbovy** [comment]
> Regarding the 1st render, I guess I could add a code cell in the notebook (below the one that outputs the canvas) that triggers redrawing the canvas (that will be executed but hidden in the voila rendered dashboard).

Mmm it doesn't work. I guess a message has to come from the front-end then?!

**Comment by martinRenou** [comment]
No, it cannot work... Voila waits for the entire Notebook to be executed before creating any widget view. It will eventually be fixed when Voila will support progressive widget rendering (It's on the roadmap). 
What you could eventually do is execute this redraw in a separate thread in the last cell.

Something like:
```python
from time import sleep

class Redraw(Thread):
    def __init__(self, canvas):
        self.canvas = canvas
        super(Redraw, self).__init__()

    def run(self):
        sleep(1) // wait one or two seconds and hope for the best
        // redraw here
        // ...

Redraw(canvas).start()
```

**Comment by martinRenou** [comment]
I'm thinking of adding an event on the Canvas for when the front-end is ready, so you know when you need to redraw the Canvas. It would allow you to do that more properly.
