### ISSUE TITLE
How to get image data from the canvas

### ISSUE THREAD

**Issue by taesiri** [martinRenou/ipycanvas#46]
Hello,

First of all, thank you for your awesome project. I was wondering if there is an easy way to access pixel-level image data from the canvas? Is it possible to save/export canvas into an image? I noticed there is a method named [``create_image_data``](https://github.com/martinRenou/ipycanvas/blob/bb98ecb4258b360bcaff8e7bd6205a96eaacd891/ipycanvas/canvas.py#L350), but it only returns a zero numpy array.

**Comment by martinRenou** [comment]
Hello, thanks for your kind words!

It is not supported yet, I'm planning on adding this in the next release 😊 I opened an issue for that #32

**Comment by taesiri** [comment]
Oh! I didn't see that issue. I'm gonna close this issue and will keep an eye on that one.

Keep up the good work 👍🏻
