### ISSUE TITLE
Canvas.clear() not permanent.

### ISSUE THREAD

**Issue by JohnGood** [martinRenou/ipycanvas#57]
After calling clear() and then drawing new vectors, all the old drawing reappears as well.   How do I truly get rid of it?

**Comment by martinRenou** [comment]
Thanks for opening an issue, would you mind providing a piece of code that reproduces the issue?

**Comment by JohnGood** [comment]
# Code to reproduce issue

from ipycanvas import Canvas

canvas = Canvas(size=(800, 800))

canvas.stroke_style = 'red'

def handle_mouse_down(x, y):
    canvas.line_to(x,y)
    canvas.stroke()

canvas.on_mouse_down(handle_mouse_down)

canvas

# Click a few random locations on the canvas, 
# then in a new cell run canvas.clear() and
# finally click a few more locations.

**Comment by martinRenou** [comment]
If you look at the documentation, the `line_to` method `Adds a straight line to the current path by connecting the path’s last point to the specified (x, y) coordinates.` 

So here you are making a long path made of multiple lines. And every time you add a new line to your path you redraw the entire path using `stroke`. So even if you clear it and then redraw a new line you will end up redrawing the entire path again.

I suppose what you are trying to achieve is the following:
```Python
from ipycanvas import Canvas

canvas = Canvas(size=(800, 800))

canvas.stroke_style = 'red'

previous_position = None

def handle_mouse_down(x, y):
    global previous_position

    if previous_position is None:
        previous_position = (x, y)
    else:
        canvas.begin_path()
        canvas.move_to(previous_position[0], previous_position[1])
        canvas.line_to(x, y)
        canvas.stroke()
        canvas.close_path()

        previous_position = (x, y)

canvas.on_mouse_down(handle_mouse_down)

canvas
```

**Comment by martinRenou** [comment]
Closing this as it is not really an issue. Feel free to ask more questions here though :)
