### ISSUE TITLE
Add suport for touch event callbacks

### ISSUE THREAD

**Issue by 0Hughman0** [martinRenou/ipycanvas#62]
Hiya,

Love the library - interactive notebooks are the future! 

I managed to whip up a really simple drawing-pad program on my laptop that worked well in Jupyter Lab, however when I tried loading the same notebook on a tablet (tried Firefox and Chrome) whilst it seems like `mouse_down` events are triggered, dragging didn't work, so drawing didn't work. I wonder whether adding the set of Touch Events might solve this problem: 
https://developer.mozilla.org/en-US/docs/Web/Events#Touch_events

Thanks,

Hugh

**Comment by martinRenou** [comment]
Hey!

Yes, it would be a nice addition indeed :)

Thanks for opening this issue
