### ISSUE TITLE
Widget state not being saved correctly

### ISSUE THREAD

**Issue by janfreyberg** [martinRenou/ipycanvas#64]
Hi there,

I am working on using ipycanvas for a data annotation widget. Typically, I document my widget packages by:

- writing a jupyter notebook with the widgets in
- executing them manually (once)
- saving them using the jupyter notebook `Widgets > Save widget state` functionality
- include them in my sphinx documentation using nbsphinx

This works well for some widgets (e.g. [here](https://superintendent.readthedocs.io/en/latest/labelling-data.html#Getting-started:-labelling-data-points), where the buttons are still interactive).

However, when I try and do this with `ipycanvas` widgets (I am nesting a MultiCanvas inside a VBox), the widgets are not displayed properly.

Is there an issue there that I'm missing? Do I need to do anything "special" to include ipycanvas widgets? Or is it an ipycanvas bug?

Thanks very much,
Jan

**Comment by martinRenou** [comment]
Hi,

Yes, it is an ipycanvas limitation. Basically, the canvas pixels are not part of the widget model (not part of the state). This is the reason why you can't retrieve pixel colors from Python, at least not by default.

The reason for this decision is that you don't always (I guess you usually don't?) need the image to be part of the state. And it would slow down the back-end/front-end communication too much.

You can actually specify that you want the canvas state to be synchronized doing: `Canvas(sync_image_data=True)`

Unfortunately, that would not fix your issue, it only allows front-end -> back-end communication but not the other way.

I can come up with a PR, that would hopefully fix your use case :)

**Comment by martinRenou** [comment]
But please keep in mind that, because you don't have a living kernel in the case of documentation, the canvas will not be responsive at all. It will be basically just a static image.

**Comment by janfreyberg** [comment]
Thanks - yes, I tried using `sync_image_data` and like you say this doesn't solve the issue. And really, the static image is all I would want - it's mainly so I can (programatically) show what a canvas onto which I've drawn a few things would look like.

**Comment by martinRenou** [comment]
This is now fixed in `0.4.2`! Please give it a try :)

It is available with `pip`, not yet with `conda`. You need to set `sync_image_data` to `True` on your canvas for it to work.

**Comment by janfreyberg** [comment]
awesome, I'll give it a go as soon as I can!
