### ISSUE TITLE
MultiCanvas Importerror on Binder

### ISSUE THREAD

**Issue by lexnederbragt** [martinRenou/ipycanvas#7]
On my Binder instance, in the notebook MultiCanvas.ipynb, the command `from ipycanvas import MultiCanvas`leads to 

```
ImportError: cannot import name 'MultiCanvas' from 'ipycanvas' (/srv/conda/envs/notebook/lib/python3.7/site-packages/ipycanvas/__init__.py)
```

**Comment by martinRenou** [comment]
Yes! It is still on the master branch and not yet in a released version :) But that should come very soon. I'll make the changed so that the Notebook for the MultiCanvas is not on the binder :) Thanks for the report

**Comment by martinRenou** [comment]
ipycanvas `0.2.2` is out! It comes with the `MultiCanvas`, the binder is now working :)
https://mybinder.org/v2/gh/martinRenou/ipycanvas/stable?filepath=examples

Thanks!
