### ISSUE TITLE
Conda package 0.4.4 is broken

### ISSUE THREAD

**Issue by LunarWatcher** [martinRenou/ipycanvas#81]
I got a fresh install of both jupyter notebook, conda, and ipycanvas. ipycanvas, however, doesn't work:

```
404 GET /static/ipycanvas.js?v=20200328182705
```

Related JS output:
```
The resource from “http://localhost:8888/static/ipycanvas.js?v=20200328182705” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
Untitled.ipynb
Loading failed for the <script> with source “http://localhost:8888/static/ipycanvas.js?v=20200328182705”. Untitled.ipynb:1:1
Could not instantiate widget manager-base.js:273
Error: "Could not create a model."
    v utils.js:119
utils.js:119
Couldn't process kernel message Error: "Script error for "ipycanvas"
http://requirejs.org/docs/errors.html#scripterror"
    makeError http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    onScriptError http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735
main.min.js:48686:42
Error: Script error for "ipycanvas"
http://requirejs.org/docs/errors.html#scripterror 2 require.js:168:17
Source map error: Error: request failed with status 404
Resource URL: http://localhost:8888/static/notebook/js/main.min.js?v=fd76f62c63dfcfdb33c73b0d15290316
Source Map URL: main.min.js.map
```

(presumably related to ipycanvas' JS file not existing)

My last runs were against examples copied straight from the docs, to eliminate coding errors on my side, before I noticed the 404 on the JS file. The python class itself imports fine though, so it looks like it's just a rendering issue. 

I'm assuming there's a config/install error on my part, but I'm not sure where. I followed the docs, but it doesn't properly install it. If relevant, I also installed ipywidgets after ipycanvas (I reinstalled ipycanvas afterwards just to see if that was relevant, but after testing), but ipywidgets works as expected (and the widgets actually appear). ipycanvas is still broken, and I'm not sure why. 

I'm also not sure what info is needed to debug this, so if you need anything else, just tell me and I'll grab it. Running Linux Mint 19.3 x64 with the latest versions I can get my hands on of all the packages.

**Comment by martinRenou** [comment]
Thanks for opening an issue. Would you mind telling me how you installed everything?

And are you using Jupyter Notebook or JupyterLab?

**Comment by LunarWatcher** [comment]
Like I said, I use Jupyter Notebook. 

Anaconda installed with:

```
 wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh && ./Anaconda3-2020.02-Linux-x86_64.sh
```

Jupyter force updated with:

```
conda install --update-all jupyter 
```

Jupyter version:

```
jupyter core     : 4.6.1
jupyter-notebook : 6.0.3
qtconsole        : 4.7.2
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.1.0
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3
```

ipycanvas installed with: 
```
conda install -c conda-forge ipycanvas
```

To work around an inclusion issue (Jupyter got a bad path, couldn't find ipycanvas), I had to reinstall the kernel:

```
ipykernel install --user
```

(Additional context: the packages were installed separately over a couple weeks, because I had unrelated problems that prevented me from using Jupyter at all. That was an HTTP protocol version issue, so it wasn't an issue with the jupyter core itself. It shouldn't have had any effect on later installs)

**Comment by martinRenou** [comment]
Can you show me the output of
```
which jupyter
```
and
```
jupyter nbextension list
```

**Comment by martinRenou** [comment]
> To work around an inclusion issue (Jupyter got a bad path, couldn't find ipycanvas), I had to reinstall the kernel

This sounds bad. If your jupyter is not installed in the expected path, I don't think the ipycanvas nbextension could be installed correctly.

**Comment by LunarWatcher** [comment]
When I say bad path, I mean that Jupyter got a PATH variable that didn't include Anaconda's packages. That caused an initial failure where ipycanvas wasn't detected in code. Could of course be related, I have no idea. 

Anyway:

```
❯ which jupyter
/home/lunarwatcher/anaconda3/bin/jupyter
❯ jupyter nbextension list 
Known nbextensions:
  config dir: /home/lunarwatcher/anaconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

**Comment by martinRenou** [comment]
Yeah, something went wrong during the installation. Not entirely sure what. But the nbextension for ipycanvas has not been installed. I suspect you have two jupyter installed.

Try doing:
```
jupyter nbextension install --py --sys-prefix ipycanvas
jupyter nbextension enable --py --sys-prefix ipycanvas
```

And restart jupyter.

**Comment by LunarWatcher** [comment]
Now, this is interesting:

```
❯ jupyter nbextension install --py --sys-prefix ipycanvas         
jupyter nbextension enable --py --sys-prefix ipycanvas
Installing /home/lunarwatcher/anaconda3/lib/python3.7/site-packages/ipycanvas/nbextension/static -> ipycanvas
Copying: /home/lunarwatcher/anaconda3/lib/python3.7/site-packages/ipycanvas/nbextension/static -> /home/lunarwatcher/anaconda3/share/jupyter/nbextensions/ipycanvas
Traceback (most recent call last):
  File "/home/lunarwatcher/anaconda3/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/lunarwatcher/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/lunarwatcher/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/lunarwatcher/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 983, in start
    super(NBExtensionApp, self).start()
  File "/home/lunarwatcher/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 257, in start
    self.subapp.start()
  File "/home/lunarwatcher/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 711, in start
    self.install_extensions()
  File "/home/lunarwatcher/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 690, in install_extensions
    **kwargs
  File "/home/lunarwatcher/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 220, in install_nbextension_python
    destination=dest, logger=logger
  File "/home/lunarwatcher/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 194, in install_nbextension
    _maybe_copy(src, full_dest, logger=logger)
  File "/home/lunarwatcher/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 1041, in _maybe_copy
    shutil.copy2(src, dest)
  File "/home/lunarwatcher/anaconda3/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/lunarwatcher/anaconda3/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lunarwatcher/anaconda3/lib/python3.7/site-packages/ipycanvas/nbextension/static'
Enabling notebook extension ipycanvas/extension...
      - Validating: problems found:
        - require?  X ipycanvas/extension
```

```
❯ ls ~/anaconda3/lib/python3.7/site-packages/ipycanvas/nbextension 
__init__.py  __pycache__
```

files appear to be missing

**Comment by martinRenou** [comment]
:confused:  Which version of ipycanvas are you using?

**Comment by martinRenou** [comment]
```python
from ipycanvas import _version

print(_version.version_info)
```

**Comment by LunarWatcher** [comment]
From the code:
```
(0, 4, 4)
```

From `conda list | grep ipycanvas`:

```
ipycanvas                 0.4.4                      py_0    conda-forge
```

**Comment by martinRenou** [comment]
Woaw. Ok, this needs to be fixed.

The latest `ipycanvas` version does not ship the nbextension :confused:.

I'm gonna fix this. In the meantime, try doing:
```
conda install -c conda-forge ipycanvas=0.4.3
```

**Comment by LunarWatcher** [comment]
That appears to be it. Works with 0.4.3 (and it enabled itself automatically this time).

**Comment by martinRenou** [comment]
Thanks a lot for reporting this. This is really helpful. It's been almost a month since it's broken and I did not see it. 

Let's keep this issue open until 0.4.4 is fixed.

**Comment by martinRenou** [comment]
I am not sure yet where the issue comes from. The PyPi package looks fine, only the conda package is broken.

https://github.com/conda-forge/ipycanvas-feedstock/pull/16

**Comment by martinRenou** [comment]
This is coming from a TypeScript error since the `@jupyter-widgets/jupyterlab-manager`. The conda recipe fails silently (not anymore since I just added tests).

We'll need to make an ipycanvas `0.4.5` and mark `0.4.4` as broken.

**Comment by martinRenou** [comment]
`0.4.5` should be out and working on `conda` very soon. I will tag `0.4.4` as broken.
