### ISSUE TITLE
mouse events delayed

### ISSUE THREAD

**Issue by ej-santoemma** [martinRenou/ipycanvas#84]
Martin, I found a strange behavior.
It seems that the event's callback function is called all at once after the last canvas operation

ubuntu 16.04
chrome 80.0.3987.163
ipycanvas 0.4.3
ipython 7.9.0
python 3.6.7

Look at this code:

```python
from ipycanvas import Canvas, hold_canvas
import time

ctx = Canvas(width=30, height=30)
def draw():
    ctx.clear_rect(0, 0, 30, 30)

    ctx.fill_style = 'rgba(0, 0, 0, 0.4)'

    ctx.begin_path()
    ctx.arc(15, 15, 10, 0, 3.14 * 2, False)
    ctx.stroke()

ctx
```

```python
tracker = []

def mouse_up(x, y):
    tracker.append(('event', time.time()))
ctx.on_mouse_up(mouse_up)

tracker.append(('begin', time.time()))
for i in range(200):
    if i == 100:
        tracker.append(('@100', time.time()))
    with hold_canvas(ctx):
        draw()
    time.sleep(0.1)
tracker.append(('end', time.time()))
```

During the ```for``` I click 4 times, a second from each other
This is the content of ```tracker```. The callback is called at the same second.
```
[('begin', 1586535083.212178),
 ('@100', 1586535093.3813028),
 ('end', 1586535103.5517037),
 ('event', 1586535103.5942726),
 ('event', 1586535103.6389883),
 ('event', 1586535103.697385),
 ('event', 1586535103.7318618)]
```

**Comment by martinRenou** [comment]
Mmmh. Try running you for-loop in a specific thread, I suppose it would work as expected in this case. The thing is the callback is called in the same process and thread, which is currently blocked on your for-loop. If I am correct this has nothing to do with ipycanvas, it is the kernel (mis?)behavior.

Please look at the Game of life example on the repo for threading example.

**Comment by ej-santoemma** [comment]
Yes, sounds correct.
I'm closing it
