### ISSUE TITLE
Example for interactively controlling an animation/games

### ISSUE THREAD

**Issue by tomanizer** [martinRenou/ipycanvas#85]
I have managed to create smooth physics animations within jupyter using ipcanvas. I have also managed to successfully use ipyevents on ipycanvas to trigger events.

However I am struggling to combine events  within animation loop. This would be required to run a game on ipycanvas, for example when pressing keys to change the direction of a spaceship flying across the canvas.

When the animation loop is running, it appears to block the events from being processed.

I can run my animation like this:

```python
def run_game():
    for i in range(5000):
        with hold_canvas(space):
            space.clear()
            space.fill_style = 'black'
            space.fill_rect(0,0, width, height)
            ship.update()
            space.fill_style = 'white'
            space.fill_arc(ship.position.x, ship.position.y, ship.size, 0, math.pi * 2)
```

And I can specify an event changing the ship's velocity like this:
```python
from ipyevents import Event 
d = Event(source=space, watched_events=['keydown'])
d.on_dom_event(ship.thrusting)
```

Each one works on their own, but the event does not fire while the run_game() is running because it is blocking.

Is there a way to run this asynchronously?

Could you perhaps provide an example, which shows how one would write a game for ipycanvas?

**Comment by martinRenou** [comment]
Thank you for opening an issue.

You have an example on the repo of the [game of life](https://github.com/martinRenou/ipycanvas/blob/master/examples/conways_game_of_life.ipynb), it's not a game per se, but it does what you want, which is running the rendering loop in a specific thread so that it won't block your events :)

**Comment by tomanizer** [comment]
Thanks Martin. I did have a look at it.
The game of life uses the Multicanvas and allows you to change one  canvas while the other keeps rendering. This is different from controlling or influencing a player object using events  on a specific canvas.
e.g. I want my spaceship to move in each animation frame with a constant speed, but I want to be able to change its direction using ipyevents. That's why I cannot render the spaceship on one canvas and use events to manipulate another.
I would probably need to introduce some sort of  async loop, where after every render on he canvas it yields to check if an event has changed the direction of my spaceship.

**Comment by martinRenou** [comment]
> The game of life uses the Multicanvas and allows you to change one canvas while the other keeps rendering. This is different from controlling or influencing a player object using events on a specific canvas.

This is detail, the example just shows you that because the rendering is happening in a specific thread, you can still execute Python code (like updating another canvas, or in your case updating your ship position).

I came up with a small Game which is pretty much what you want, but the ship follows the mouse.

```python
from time import sleep
from threading import Thread

import numpy as np

from ipycanvas import MultiCanvas, hold_canvas


# Ship draw function
def draw(ship, canvas, color='black'):
    with hold_canvas(canvas):
        canvas.clear()
        canvas.fill_style = color

        canvas.fill_rect(ship.x, ship.y, 20)

# Create the canvas
multi = MultiCanvas(2, width=800, height=600)
multi[0].fill_style = '#FFF0C9'
multi[0].fill_rect(0, 0, 800, 600)

# Create the ship
class Ship():
    def __init__(self, x, y):
        self.x = x
        self.y = y

ship = Ship(50, 50)

# Deal with mouse events
def update_ship_position(x, y):
    ship.x = x
    ship.y = y

multi[1].on_mouse_move(update_ship_position)

# Create the threaded game
class Game(Thread):
    def __init__(self, ship, canvas):
        self.ship = ship
        self.canvas = canvas

        super(Game, self).__init__()

    def run(self):
        while(True):
            draw(self.ship, self.canvas, '#5770B3')

            sleep(0.1)

Game(ship, multi[1]).start()

multi
```

**Comment by tomanizer** [comment]
Martin, you are amazing. Thanks a lot for this example! And for you work on ipycanvas.
I want to use it for teaching kids. and the interactivity and graphics within a notebook make a real difference there.

**Comment by martinRenou** [comment]
Thanks! I hope you'll find everything you need. Don't hesitate to open other issues for feature requests, or other questions.

**Comment by ej-santoemma** [comment]
@martinRenou keep this open, I guess this is one of the first things a new user encouters with ipycanvas. You could mark it as [doc]

@tomanizer see if this [gist](https://gist.github.com/ej-santoemma/0ab67d4ae726a60de297e289ff887ebc) may help you.
It's a SimpleAnimator class with usage at the end of the file.
It handles the thread termination properly and let you see the exceptions during debugging

I'd put the ```draw()``` function in a class, together with methods like ```enter_scene()``` and ```leave_scene()``` and the methods to move objects on scene

**Comment by martinRenou** [comment]
> I guess this is one of the first things a new user encouters with ipycanvas

I agree. It should be added to the documentation then :)
